#!/bin/bash
# MikroTik SNMP Configuration Commands
# Copy and paste these commands to your MikroTik terminal

echo "==================================================================="
echo "  MIKROTIK SNMP CONFIGURATION"
echo "==================================================================="
echo ""
echo "1. Enable SNMP Service:"
echo "   /snmp set enabled=yes"
echo ""
echo "2. Set SNMP Community (default: public):"
echo "   /snmp community set [find name=public] addresses=0.0.0.0/0"
echo ""
echo "3. Verify SNMP is enabled:"
echo "   /snmp print"
echo ""
echo "4. Test from billing server:"
echo "   snmpwalk -v2c -c public 172.22.10.156 1.3.6.1.2.1.2.2.1.2"
echo ""
echo "==================================================================="
echo ""
echo "⚠️  SECURITY NOTE:"
echo "   - Change 'public' to a secure community string in production"
echo "   - Restrict addresses to your billing server IP only"
echo "   - Example: addresses=172.22.10.28/32"
echo ""
echo "==================================================================="
