#!/bin/bash

echo "==================================================================="
echo "MIKROTIK PPP PROFILE CHECK - Untuk Troubleshoot IP 0.0.0.0"
echo "==================================================================="
echo ""
echo "RADIUS Server sudah bekerja dengan baik dan mengirim:"
echo "  ✅ Service-Type = Framed-User"
echo "  ✅ Framed-Protocol = PPP"
echo "  ✅ Mikrotik-Group = UpTo-10M"
echo ""
echo "Tapi client dapat IP 0.0.0.0 dan disconnect berulang."
echo "Ini berarti PPP Profile di MikroTik belum dikonfigurasi dengan benar."
echo ""
echo "==================================================================="
echo "LANGKAH-LANGKAH PERBAIKAN DI MIKROTIK"
echo "==================================================================="
echo ""
echo "1. Login ke MikroTik via SSH atau Winbox"
echo ""
echo "2. Cek apakah PPP Profile 'UpTo-10M' sudah ada:"
echo ""
echo "   /ppp profile print detail where name=UpTo-10M"
echo ""
echo "   Kalau tidak ada output, profile belum dibuat!"
echo ""
echo "3. Buat PPP Profile (kalau belum ada):"
echo ""
echo "   /ppp profile add name=UpTo-10M \\"
echo "       local-address=10.10.10.1 \\"
echo "       remote-address=pool-10M \\"
echo "       rate-limit=10M/10M \\"
echo "       only-one=yes"
echo ""
echo "4. Buat IP Pool untuk client:"
echo ""
echo "   /ip pool add name=pool-10M ranges=10.10.10.10-10.10.10.254"
echo ""
echo "5. Verifikasi konfigurasi:"
echo ""
echo "   /ppp profile print detail where name=UpTo-10M"
echo ""
echo "   Output harus menampilkan:"
echo "   - local-address: 10.10.10.1"
echo "   - remote-address: pool-10M"
echo "   - rate-limit: 10M/10M"
echo ""
echo "6. Restart koneksi PPPoE client dan cek ulang:"
echo ""
echo "   /ppp active print detail"
echo ""
echo "   Sekarang harusnya Remote Address tidak lagi 0.0.0.0"
echo ""
echo "==================================================================="
echo "CATATAN PENTING"
echo "==================================================================="
echo ""
echo "• Nama profile HARUS SAMA PERSIS (case sensitive):"
echo "  - Di database: 'UpTo-10M'"  
echo "  - Di MikroTik: 'UpTo-10M'"
echo ""
echo "• local-address = IP gateway untuk client (biasanya .1)"
echo "• remote-address = pool atau range IP untuk client"
echo ""
echo "• Kalau ada paket lain (Bronze, Silver, Gold), masing-masing"
echo "  perlu profile sendiri dengan IP pool berbeda!"
echo ""
echo "==================================================================="
echo "CONTOH UNTUK MULTIPLE PROFILE"
echo "==================================================================="
echo ""
echo "# Profile Bronze (5Mbps)"
echo "/ppp profile add name=Bronze local-address=10.10.20.1 remote-address=pool-bronze rate-limit=5M/5M"
echo "/ip pool add name=pool-bronze ranges=10.10.20.10-10.10.20.254"
echo ""
echo "# Profile Silver (20Mbps)"
echo "/ppp profile add name=Silver local-address=10.10.30.1 remote-address=pool-silver rate-limit=20M/20M"
echo "/ip pool add name=pool-silver ranges=10.10.30.10-10.10.30.254"
echo ""
echo "# Profile Gold (50Mbps)"
echo "/ppp profile add name=Gold local-address=10.10.40.1 remote-address=pool-gold rate-limit=50M/50M"
echo "/ip pool add name=pool-gold ranges=10.10.40.10-10.10.40.254"
echo ""
echo "==================================================================="
echo ""
echo "Setelah konfigurasi di MikroTik selesai, disconnect dan reconnect"
echo "client PPPoE, kemudian cek dashboard RADIUS di:"
echo ""
echo "  http://$(hostname -I | awk '{print $1}'):3000/admin/radius"
echo ""
echo "Widget 'Active Sessions' harusnya sekarang menampilkan IP yang benar."
echo ""
echo "==================================================================="
