sql {
    driver = "rlm_sql_postgresql"
    dialect = "postgresql"

    # Connection info
    server = "172.22.10.28"
    port = 5432
    login = "kilusi_user"
    password = "kilusi123"
    radius_db = "kilusi_bill"

    # Connection pool
    pool {
        start = 5
        min = 4
        max = 50
        spare = 10
        uses = 0
        retry_delay = 30
        lifetime = 0
        idle_timeout = 60
    }

    # Read clients from database
    read_clients = yes
    client_table = "nas_servers"

    # Query configuration
    $INCLUDE ${modconfdir}/sql/main/${dialect}/queries.conf
}