'use client'

import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Server } from 'lucide-react'

// Types
import { NAS, NASFormData } from './types'

// Hooks
import { useNASList } from './hooks/useNASList'

// Components
import { NASStats } from './components/NASStats'
import { NASToolbar } from './components/NASToolbar'
import { NASList } from './components/NASList'
import { NASFormModal } from './components/NASFormModal'
import { NASDetailModal } from './components/NASDetailModal'

export default function RadiusPage() {
  // Use custom hook for NAS list management
  const {
    nasList,
    snmpStats,
    loading,
    error,
    testLoading,
    fetchNAS,
    createNAS,
    updateNAS,
    deleteNAS,
    deleteMultipleNAS,
    testConnection,
    bulkAction
  } = useNASList()

  // Local state
  const [searchTerm, setSearchTerm] = useState('')
  const [selectedNAS, setSelectedNAS] = useState<string[]>([])

  // Modal states
  const [showFormModal, setShowFormModal] = useState(false)
  const [editingNAS, setEditingNAS] = useState<NAS | null>(null)
  const [showDetailModal, setShowDetailModal] = useState(false)
  const [detailNAS, setDetailNAS] = useState<NAS | null>(null)

  // Handlers
  const handleView = (nas: NAS) => {
    setDetailNAS(nas)
    setShowDetailModal(true)
  }

  const handleEdit = (nas: NAS) => {
    setEditingNAS(nas)
    setShowFormModal(true)
  }

  const handleDelete = async (nas: NAS) => {
    if (confirm(`Are you sure you want to delete NAS "${nas.shortname}"?`)) {
      try {
        await deleteNAS(nas.id)
      } catch (error) {
        const err = error as Error
        alert(err.message || 'Failed to delete NAS')
      }
    }
  }

  const handleTest = async (id: string) => {
    const result = await testConnection(id)
    if (!result.success) {
      alert(`Connection test failed: ${result.message}`)
    }
  }

  const handleSave = async (data: NASFormData, isEdit: boolean, id?: string) => {
    if (isEdit && id) {
      await updateNAS(id, data)
    } else {
      await createNAS(data)
    }
  }

  const handleCreate = () => {
    setEditingNAS(null)
    setShowFormModal(true)
  }

  const handleBulkDelete = async () => {
    if (selectedNAS.length === 0) return
    if (confirm(`Are you sure you want to delete ${selectedNAS.length} NAS servers?`)) {
      try {
        await deleteMultipleNAS(selectedNAS)
        setSelectedNAS([])
      } catch (error) {
        const err = error as Error
        alert(err.message || 'Failed to delete NAS')
      }
    }
  }

  const handleBulkActivate = async () => {
    try {
      await bulkAction(selectedNAS, 'activate')
      setSelectedNAS([])
    } catch (error) {
      const err = error as Error
      alert(err.message || 'Failed to activate NAS')
    }
  }

  const handleBulkDeactivate = async () => {
    try {
      await bulkAction(selectedNAS, 'deactivate')
      setSelectedNAS([])
    } catch (error) {
      const err = error as Error
      alert(err.message || 'Failed to deactivate NAS')
    }
  }

  // Generate MikroTik script for NAS
  const generateMikrotikScript = (nas: NAS): string => {
    const serverIP = typeof window !== 'undefined' ? window.location.hostname : '192.168.1.1'
    const snmpCommunity = nas.snmp_community || 'kilusibill'
    const snmpCommunityTrap = nas.snmp_community_trap || 'kilusibill'

    return `# MikroTik Configuration Script
# Generated by Kilusi Bill ISP Management System
# NAS Server: ${nas.shortname}
# IP Address: ${nas.nasname}
# Server IP: ${serverIP}
# Generated: ${new Date().toLocaleString('id-ID')}

# add SNMP
/snmp community
set [ find default=yes ] disabled=yes write-access=no
rem [find name!=public]
add addresses=${serverIP} name=${snmpCommunity} write-access=yes
/snmp
set enabled=yes trap-community=${snmpCommunityTrap} trap-version=2

/system identity
set name="${nas.shortname}"

# Update NTP
/system ntp client server rem [find]
/system ntp client set enabled=yes server=162.159.200.1,162.159.200.123

# Script Radius
/radius
rem [find]
add address=${serverIP} comment=kilusirad authentication-port=1812 accounting-port=1813 secret="${nas.secret}" service=ppp,login src-address=${nas.nasname} timeout=3s
/radius
set require-message-auth=no num=0

/ppp aaa
set use-radius=yes accounting=yes
set interim-update=0s
`
  }

  const handleDownloadScript = (nas: NAS) => {
    try {
      const scriptContent = generateMikrotikScript(nas)
      const blob = new Blob([scriptContent], { type: 'text/plain' })
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `mikrotik-nas-${nas.shortname.toLowerCase().replace(/\s+/g, '-')}.txt`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      window.URL.revokeObjectURL(url)
    } catch (error) {
      alert('Error downloading script')
      console.error('Download error:', error)
    }
  }

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Page Header */}
      <div className="text-center">
        <h1 className="text-xl sm:text-2xl font-semibold text-foreground">RADIUS Management</h1>
        <p className="text-sm sm:text-base text-muted-foreground">
          Kelola Network Access Server (NAS) dan monitoring SNMP
        </p>
      </div>

      {/* Stats Cards */}
      <NASStats nasList={nasList} />

      {/* NAS List Section */}
      <Card>
        <CardHeader className="pb-3 sm:pb-6">
          <CardTitle className="flex items-center space-x-2 text-base sm:text-lg">
            <Server className="h-4 w-4 sm:h-5 sm:w-5" />
            <span>Daftar Network Access Server</span>
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-0">
          {/* Toolbar */}
          <NASToolbar
            searchTerm={searchTerm}
            onSearchChange={setSearchTerm}
            selectedCount={selectedNAS.length}
            onRefresh={fetchNAS}
            onCreate={handleCreate}
            onBulkDelete={handleBulkDelete}
            onBulkActivate={handleBulkActivate}
            onBulkDeactivate={handleBulkDeactivate}
            loading={loading}
          />

          {/* NAS List */}
          <NASList
            nasList={nasList}
            snmpStats={snmpStats}
            loading={loading}
            error={error}
            testLoading={testLoading}
            searchTerm={searchTerm}
            onView={handleView}
            onEdit={handleEdit}
            onDelete={handleDelete}
            onTest={handleTest}
            onDownloadScript={handleDownloadScript}
            onRetry={fetchNAS}
          />
        </CardContent>
      </Card>

      {/* Form Modal (Create/Edit) */}
      <NASFormModal
        open={showFormModal}
        onClose={() => { setShowFormModal(false); setEditingNAS(null) }}
        editingNAS={editingNAS}
        onSave={handleSave}
      />

      {/* Detail Modal */}
      <NASDetailModal
        nas={detailNAS}
        open={showDetailModal}
        onClose={() => { setShowDetailModal(false); setDetailNAS(null) }}
        onEdit={handleEdit}
      />
    </div>
  )
}